PROJECT_NAME = LOGIN 
SOURCE = login.c
CC = gcc 
PROJECT_OUTPUT = $
{PROJECT_NAME}.out 
build: $(SOURCE) 
$(CC) $(SOURCE) -o $(PROJECT_OUTPUT) run:$(PROJECT_OUTPUT) ./$(PROJECT_OUTPUT) 
clean: rm *.out 
doc: make -C documentation
